name: 'AxolotlCheatDetector'
version: 1.4.5
description: 'Prevent your axolotls from cheating!'
author: OMGPandaYT
main: me.omgpandayt.acd.ACD
api-version: 1.17


commands:
   alerts:
      description: Toggle alerts on and off
      usage: /<command>
      permission: acd.notify