name: AxolotlCheatDetector
version: 1.3.4-BETA
description: An anticheat for preventing your baby axolotls from cheating!
author: OMGPandaYT
main: me.omgpandayt.acd.ACD
api-version: 1.17


commands:
   alerts:
      description: Toggle alerts on and off
      usage: /<command>
      permission: acd.notify