name: 'AxolotlCheatDetector'
version: 1.4.7.1
description: 'Prevent your baby axolotls from cheating!'
author: OMGPandaYT
main: me.omgpandayt.acd.ACD
api-version: 1.17
load: POSTWORLD


commands:
   alerts:
      description: Toggle alerts on and off
      usage: /<command>
      permission: acd.notify